site_name: BuildableExpressions
site_description: ''
site_author: Steve Wilkes
repo_url: https://github.com/agileobjects/BuildableExpressions

docs_dir: 'docs/src'
site_dir: 'docs/site'

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/vs2015.min.css
    - https://agileobjects.co.uk/assets/css/docs-styles.min.css

extra_javascript:
    - assets/scripts/dox-cls.js
    - https://agileobjects.co.uk/assets/js/ao-docs.min.js
    
nav:
    - Building Types:
        - Overview: building-types/index.md
    - Generating Code:
        - Overview: generating-code/index.md
        - Configuration: generating-code/Configuration.md
        - Samples: generating-code/Samples.md
    - Source Code API:
        - Overview: api/index.md
        - Classes: api/Building-Classes.md
        - Structs: api/Building-Structs.md
        - Interfaces: api/Building-Interfaces.md
        - Attributes: api/Building-Attributes.md
        - Enums: api/Building-Enums.md
        - Implementing Interfaces: api/Implementing-Interfaces.md
        - Implementing Inheritance: api/Implementing-Inheritance.md
        - Generics: api/Generics.md
        - Constructors: api/Building-Constructors.md
        - Methods: api/Building-Methods.md
        - Fields: api/Building-Fields.md
        - Properties: api/Building-Properties.md
        - Documentation: api/Documentation.md

theme: readthedocs