site_name: BuildableExpressions
site_description: ''
site_author: Steve Wilkes
repo_url: https://github.com/agileobjects/BuildableExpressions

docs_dir: 'docs/src'
site_dir: 'docs/site'

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/vs2015.min.css
    - css/styles.min.css

extra_javascript:
    - scripts/docs.min.js
    
nav:
    - General Use:
        - Building types: Building-Types.md
        - Generating code: Generating-Code.md
    - Source Code API:
        - Overview: api/index.md
        - Classes: api/Building-Classes.md
        - Structs: api/Building-Structs.md
        - Interfaces: api/Building-Interfaces.md
        - Enums: api/Building-Enums.md
        - Implementing Interfaces: api/Implementing-Interfaces.md
        - Derived Types: api/Building-Derived-Types.md
        - Generics: api/Generics.md
        - Constructors: api/Building-Constructors.md
        - Methods: api/Building-Methods.md
        - Fields: api/Building-Fields.md
        - Properties: api/Building-Properties.md

theme: readthedocs