// Generated by XmlToSettingsGenerator in this project 

using System;

namespace AgileObjects.BuildableExpressions.Generator.Samples.XmlSettingsGenerator
{
    public class MySettings
    {
        public int FavouriteNumber => 12345;

        public string FavouriteCity => "Vancouver";

        public DateTime DateExpires => DateTime.Parse("2022-01-01");

    }
}